### ISSUE TITLE
kmodpy / python 3

### ISSUE THREAD

**Issue by patatetom** [cnanakos/kmodpy#2]
hi,

no problem with python2, but error with python3 :

```console
$ pip install --user kmodpy
Collecting kmodpy
  Downloading kmodpy-0.1.10.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ab5m_k_o/kmodpy/setup.py", line 24
        def isstr((k, v)):
                  ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ab5m_k_o/kmodpy/
```

regards.

**Comment by tincho9** [comment]
Fixed in https://github.com/cnanakos/kmodpy/pull/3

**Comment by daghemo** [comment]
@cnanakos, would you also release the fixed version to PyPI? :(
I think you can also add the following to setup.py, since pep-3113 has been introduced with Python 3.0:
Programming Language :: Python :: 3
Programming Language :: Python :: 3.0
Programming Language :: Python :: 3.1
Programming Language :: Python :: 3.2
Programming Language :: Python :: 3.3
Programming Language :: Python :: 3.4
Programming Language :: Python :: 3.5
Programming Language :: Python :: 3.6
Programming Language :: Python :: 3.7
Also, the version should be updated within version.py.

**Comment by cnanakos** [comment]
New package in pypi has been uploaded, version bumped and commit pushed under master branch. Thx.

**Comment by patatetom** [comment]
thanks !
```bash
$ python -V
Python 3.7.2
$ pip install --user kmodpy
Collecting kmodpy
  Downloading https://files.pythonhosted.org/packages/a5/6a/837ff0c8da94dfda3d60323377ed0b597de9c525483c2094b0e3f2240eae/kmodpy-0.1.13.tar.gz
Installing collected packages: kmodpy
  Running setup.py install for kmodpy ... done
Successfully installed kmodpy-0.1.13
```
